### ISSUE TITLE
file watcher program

### ISSUE THREAD

**Issue by nklapste** [ECE421/rash#11]
An important task in any system is to keep track of all files in existence at any point in time. In additional many security systems monitor change information in the file system to help detect erroneous alteration.
 
To help with this and other related tasks; write a reusable component(s) plus a “driver” program, which monitors files or potential files. The list of all names to be monitored is fully specified at execution time. If the file is altered, created or destroyed, the component should undertake a user specified action after an optional, but highly accurate, time delay.  Note that while these components are 'watching' the user must still be able to enter commands normally to the shell; that is, the system must be non-blocking. Think of this system as a typical batch-processing job that runs indefinitely.
 
The user-defined actions, and any time delay, must be specific to the type of alteration. That is the user must be able to specify different behavior for each type of change (altered, created or destroyed). The user must also by able to define which type of alternation to which (potential) file(name) they are interested in watching. Specifically, this component must provide a facility, which supports one of the following interface protocols – you are required to decide which one:
 ```
FileWatch(type_of_alteration, duration, list_of_filenames) { action }
```
Or, 
```
FileWatchCreation(duration, list_of_filenames) { action }
FileWatchAlter(duration, list_of_filenames) { action }
FileWatchDestroy(duration, list_of_filenames) { action } 
```

Or,  
Give us a better idea – but you will need to be convincing.

**Comment by thomaslorincz** [comment]
How do we want to handle the "user-defined" actions? My first attempts involved trying to sandbox a call to eval(action) but I haven't found a sandbox that provides the security and flexibility we may want.
Do we want to keep looking into sandboxing or should we have the user pick from a set of safe actions like printing, writing to a log file, exiting, etc.?
